-- supabase/migrations/20250716180000_create_questions_table.sql

create table public.questions (
    id bigint primary key generated by default as identity,
    institution text not null,
    year integer not null,
    subject text not null,
    topic text not null,
    statement text not null,
    image text,
    alternatives jsonb not null,
    correct_answer integer not null,
    explanation text not null,
    created_at timestamp with time zone not null default now()
);

-- Add comments for clarity
comment on column public.questions.alternatives is 'JSON array of strings representing the alternatives, e.g., ["Alt A", "Alt B"]';
comment on column public.questions.correct_answer is '0-based index of the correct alternative in the alternatives array';

-- Enable Row Level Security (RLS)
alter table public.questions enable row level security;

-- Create Policies for RLS
-- Allow public, anonymous read access to all questions
create policy "Allow public read access" on public.questions for select using (true);

-- Note: Insert, update, and delete operations will be handled by a backend script
-- using the service_role key, which bypasses RLS. This is a secure practice.
